simd binary quantization and benches
qdrant/quantization pull request #20
Opened 2023-08-25 10:46 UTC by IvanPleshkov

2023-08-30 14:08 UTC, timvisee requested changes
Nice work!

I'm not familiar with Neon instructions at all so I didn't do very deep inspection.

The only thing I'd like to see is a unit test to assert `xor_product` output is the same as the default implementation. That would ensure that the SSE/Neon implementations are correct (when tested on those platforms).

It would literally be something like:

```rust
#[test]
fn test_xor_product() {
    // Have some test data here
    for (v1, v2) in vectors {
        assert_eq!(
            EncodedVectorsBin::xor_product(&v1, &v2),
            v1.iter()
                .zip(v2)
                .map(|(b1, b2)| (b1 ^ b2).count_ones() as usize)
                .sum()
        );
    }
}
```

2023-08-30 14:08 UTC, timvisee commented on quantization/src/encoded_vectors_binary.rs
> +        }
For SSE4.1 we provide `count = 2 * v1.len()` and for Neon we provide `count = v1.len()`.

Function signatures are the same, though I see the implementations are different. Could we clarify this a bit with a comment, or by renaming one of  the `counts`?

2023-08-31 06:49 UTC, IvanPleshkov commented on quantization/src/encoded_vectors_binary.rs
> +        }
Thanks for highlighting it! In arm, we process 128-bit chunks but in x64 only 64-bit, that's why multiplication by 2 is correct. But this is an implementation detail. We shouldn't know it. Fixed by moving this multiplication to C code

2023-08-31 06:56 UTC, IvanPleshkov commented
> Nice work!
> 
> I'm not familiar with Neon instructions at all so I didn't do very deep inspection.
> 
> The only thing I'd like to see is a unit test to assert `xor_product` output is the same as the default implementation. That would ensure that the SSE/Neon implementations are correct (when tested on those platforms).
> 
> It would literally be something like:
> 
> ```rust
> #[test]
> fn test_xor_product() {
>     // Have some test data here
>     for (v1, v2) in vectors {
>         assert_eq!(
>             EncodedVectorsBin::xor_product(&v1, &v2),
>             v1.iter()
>                 .zip(v2)
>                 .map(|(b1, b2)| (b1 ^ b2).count_ones() as usize)
>                 .sum()
>         );
>     }
> }
> ```

I guess such test is not necessary. We have unit tests for binary quantization and each test covers xor. I would discuss testing of non-accelerated xor calculation but I decided to skip it. Because the implementation and test (like in your example) are absolutely the same parts of code

2023-08-31 07:59 UTC, timvisee commented on quantization/src/encoded_vectors_binary.rs
> +        }
Fantastic!

2023-08-31 08:00 UTC, timvisee approved these changes

2023-08-31 10:06 UTC, merged